In [6]:
class Employee:
    empCount = 0  # Data member to count the number of Employees

    def __init__(employer, name, family, salary, department):
        """
        Constructor to initialize name, family, salary, department
        """
        employer.name = name
        employer.family = family
        employer.salary = salary
        employer.department = department
        Employee.empCount += 1  # Increment employee count

    def avgSalary(employer):
        """
        Function to calculate average salary
        """
        return employer.salary / Employee.empCount

class FulltimeEmployee(Employee):
    """
    Fulltime Employee class inheriting from Employee class
    """
    pass

# Create instances of Employee and Fulltime Employee classes
emp1 = Employee("Ravi", "Sam", 70000, "IT")
emp2 = FulltimeEmployee("Ravi", "Sam", 50000, "Marketing")

# Call member functions
print(f"Employee Count: {Employee.empCount}")
print(f"Average Salary: ${emp1.avgSalary():.2f}")

Employee Count: 2
Average Salary: $35000.00


In [7]:
import numpy as np

In [9]:
# Create a random vector of size 20 with floats in range 1-20
array = np.random.rand(20) * 20 + 1

# Reshape the array to 4 by 5
array = array.reshape(4, 5)

# Replace the max in each row by 0 (axis=1) without using a loop
array[np.arange(array.shape[0])[:, None], np.argmax(array, axis=1)] = 0

print(array)

[[ 7.55563302  0.          0.          0.          8.53607647]
 [ 4.80984973  0.          0.          0.          6.83311141]
 [10.50785424  0.          0.          0.          3.66641356]
 [11.62746082  0.          0.          0.         14.74818484]]
